modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Apache License, Version 2.0"

[[mods]]
modId = "mpfapi"
version = "${version}"
displayName = "Multiplatform Fabric API"
authors = "PlayerXess"
description = '''
A version of the Fabric API Made To Run On All Loaders
'''
#logoFile = ""

[[dependencies.mpfapi]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mpfapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mpfapi]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
